package rules.preporukaLekova;
import com.ftn.sbnz2023tim3.model.modeli.tabele.Pregled;
import com.ftn.sbnz2023tim3.model.modeli.tabele.korisnici.Pacijent;
import com.ftn.sbnz2023tim3.model.modeli.dto.lekovi.Lek;
import com.ftn.sbnz2023tim3.model.modeli.enumeracije.Uzrast;
import com.ftn.sbnz2023tim3.model.modeli.dto.lekovi.FiltriranLek;

rule "opis_doze_rule0"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.DETE)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Methylphenidate-Ritalin", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Obično počinje sa 5 mg dva puta dnevno (pre doručka i ručka). Doza se može povećavati nedeljno za 5-10 mg/dan do maksimalno 60 mg/dan.")
    }
end

rule "opis_doze_rule1"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Methylphenidate-Ritalin", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Obično počinje sa 5 mg dva puta dnevno (pre doručka i ručka). Doza se može povećavati nedeljno za 5-10 mg/dan do maksimalno 60 mg/dan.")
    }
end

rule "opis_doze_rule2"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Methylphenidate-Ritalin", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Obično počinje sa 5 mg dva puta dnevno (pre doručka i ručka). Doza se može povećavati nedeljno za 5-10 mg/dan do maksimalno 60 mg/dan.")
    }
end

rule "opis_doze_rule3"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.DETE)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Amphetamine-Adderall", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Obično se započinje sa 5 mg jednom ili dva puta dnevno. Doza se može povećavati nedeljno za 5 mg/dan, do maksimalne doze od 30 mg/dan")
    }
end

rule "opis_doze_rule4"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Amphetamine-Adderall", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Obično se započinje sa 10 mg jednom dnevno. Doza se može povećavati nedeljno za 10 mg/dan, do maksimalne doze od 40 mg/dan.")
    }
end

rule "opis_doze_rule5"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Amphetamine-Adderall", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Obično se započinje sa 10 mg jednom dnevno. Doza se može povećavati nedeljno za 10 mg/dan, do maksimalne doze od 40 mg/dan.")
    }
end

rule "opis_doze_rule6"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.DETE)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Atomoxetine-Strattera", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Obično se započinje sa 0.5 mg/kg/dan, povećavajući do ciljane doze od 1.2 mg/kg/dan nakon minimalno 3 dana. Maksimalna doza je 1.4 mg/kg/dan ili 100 mg/dan, u zavisnosti od toga koja je manja.")
    }
end

rule "opis_doze_rule7"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Atomoxetine-Strattera", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Obično se započinje sa 40 mg/dan, povećavajući do ciljane doze od 80 mg/dan nakon minimalno 3 dana. Maksimalna doza je 100 mg/dan.")
    }
end

rule "opis_doze_rule8"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Atomoxetine-Strattera", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Obično se započinje sa 40 mg/dan, povećavajući do ciljane doze od 80 mg/dan nakon minimalno 3 dana. Maksimalna doza je 100 mg/dan.")
    }
end

rule "opis_doze_rule9"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.DETE)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Guanfacine-Intuniv", opisDoze == null)
then
    modify($lek){
        setOpisDoze(" Obično se započinje sa 1 mg/dan, sa povećanjem doze od 1 mg nedeljno, do maksimalne doze od 4 mg/dan, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule10"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Guanfacine-Intuniv", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Obično se započinje sa 1 mg/dan, sa povećanjem doze od 1 mg nedeljno, do maksimalne doze od 7 mg/dan, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule11"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.DETE)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Clonidine-Kapvay", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Obično se započinje sa 0.1 mg/dan, sa povećanjem doze od 0.1 mg nedeljno, do maksimalne doze od 0.4 mg/dan, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule12"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Clonidine-Kapvay", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Obično se započinje sa 0.1 mg/dan, sa povećanjem doze od 0.1 mg nedeljno, do maksimalne doze od 0.4 mg/dan, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule13"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.DETE)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Donepezil-Aricept", opisDoze == null)
then
    modify($lek){
        setOpisDoze("5-10 mg jednom dnevno, po mogućstvu uveče")
    }
end

rule "opis_doze_rule14"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Donepezil-Aricept", opisDoze == null)
then
    modify($lek){
        setOpisDoze("5-10 mg jednom dnevno, po mogućstvu uveče")
    }
end

rule "opis_doze_rule15"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Donepezil-Aricept", opisDoze == null)
then
    modify($lek){
        setOpisDoze("10-23 mg jednom dnevno, po mogućstvu uveče")
    }
end

rule "opis_doze_rule16"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.DETE)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Memantine-Namenda", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 3 mg jednom dnevno, postepeno se povećava na 10 mg dva puta dnevno, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule17"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Memantine-Namenda", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 5 mg jednom dnevno, postepeno se povećava na 10 mg dva puta dnevno, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule18"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Memantine-Namenda", opisDoze == null)
then
    modify($lek){
        setOpisDoze(" Početna doza je 5 mg jednom dnevno, postepeno se povećava na 10 mg dva puta dnevno, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule19"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.DETE)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Rivastigmine-Exelon", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 1.5 mg dva puta dnevno, postepeno se povećava na 6 mg dva puta dnevno, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule20"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Rivastigmine-Exelon", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 1.5 mg dva puta dnevno, postepeno se povećava na 6 mg dva puta dnevno, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule21"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Rivastigmine-Exelon", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 1.5 mg dva puta dnevno, postepeno se povećava na 6 mg dva puta dnevno, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule22"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.DETE)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Galantamine-Razadyne", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 4 mg dva puta dnevno, postepeno se povećava na 12 mg dva puta dnevno, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule23"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Galantamine-Razadyne", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 4 mg dva puta dnevno, postepeno se povećava na 12 mg dva puta dnevno, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule24"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Galantamine-Razadyne", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 4 mg dva puta dnevno, postepeno se povećava na 12 mg dva puta dnevno, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule25"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.DETE)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Combination therapy-Namzaric", opisDoze == null)
then
    modify($lek){
        setOpisDoze(" Početna doza je 2.5 mg dva puta dnevno, postepeno se povećava na 10 mg dva puta dnevno, na osnovu odgovora i podnošljivosti")
    }
end

rule "opis_doze_rule26"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Combination therapy-Namzaric", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 2.5 mg dva puta dnevno, postepeno se povećava na 10 mg dva puta dnevno, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule27"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Combination therapy-Namzaric", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 2.5 mg dva puta dnevno, postepeno se povećava na 12 mg dva puta dnevno, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule28"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Zolpidem-Ambien", opisDoze == null)
then
    modify($lek){
        setOpisDoze("5 mg za žene, 5-10 mg za muškarce, uzeti jednom dnevno neposredno pre spavanja.")
    }
end

rule "opis_doze_rule29"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Zolpidem-Ambien", opisDoze == null)
then
    modify($lek){
        setOpisDoze("5 mg za žene, 5-10 mg za muškarce, uzeti jednom dnevno neposredno pre spavanja.")
    }
end

rule "opis_doze_rule30"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Eszopiclone-Lunesta", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 1 mg, uzeta jednom dnevno neposredno pre spavanja; može se povećati na 2-3 mg na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule31"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Eszopiclone-Lunesta", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 1 mg, uzeta jednom dnevno neposredno pre spavanja; može se povećati na 2-3 mg na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule32"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Zaleplon-Sonata", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 5-10 mg, uzeta jednom dnevno neposredno pre spavanja; doza se može povećati na 20 mg na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule33"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Zaleplon-Sonata", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 5-10 mg, uzeta jednom dnevno neposredno pre spavanja; doza se može povećati na 20 mg na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule34"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Ramelteon-Rozerem", opisDoze == null)
then
    modify($lek){
        setOpisDoze("8 mg, uzet jednom dnevno neposredno pre spavanja.")
    }
end

rule "opis_doze_rule35"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Ramelteon-Rozerem", opisDoze == null)
then
    modify($lek){
        setOpisDoze("8 mg, uzet jednom dnevno neposredno pre spavanja.")
    }
end

rule "opis_doze_rule36"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Trazodone-Desyrel", opisDoze == null)
then
    modify($lek){
        setOpisDoze("25-100 mg, uzet jednom dnevno neposredno pre spavanja; doze mogu biti različite.")
    }
end

rule "opis_doze_rule37"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Trazodone-Desyrel", opisDoze == null)
then
    modify($lek){
        setOpisDoze("25-100 mg, uzet jednom dnevno neposredno pre spavanja; doze mogu biti različite.")
    }
end

rule "opis_doze_rule38"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.DETE)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Levetiracetam-Keppra", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 500 mg dva puta dnevno, uz moguće povećanje do maksimalne doze od 2,000 mg/dan, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule39"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Levetiracetam-Keppra", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 500 mg dva puta dnevno, uz moguće povećanje do maksimalne doze od 3,000 mg/dan, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule40"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Levetiracetam-Keppra", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 500 mg dva puta dnevno, uz moguće povećanje do maksimalne doze od 3,000 mg/dan, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule41"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.DETE)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Lamotrigine-Lamictal", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Doziranje je kompleksno i varira u zavisnosti od istovremenih lekova i individualnog odgovora.")
    }
end

rule "opis_doze_rule42"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Lamotrigine-Lamictal", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Doziranje je kompleksno i varira u zavisnosti od istovremenih lekova i individualnog odgovora.")
    }
end

rule "opis_doze_rule43"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Lamotrigine-Lamictal", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Doziranje je kompleksno i varira u zavisnosti od istovremenih lekova i individualnog odgovora.")
    }
end

rule "opis_doze_rule44"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.DETE)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Carbamazepine-Tegretol", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 100-150 mg dva puta dnevno, uz moguće povećanje do maksimalne doze od 1,000 mg/dan, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule45"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Carbamazepine-Tegretol", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 100-200 mg dva puta dnevno, uz moguće povećanje do maksimalne doze od 1,200 mg/dan, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule46"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Carbamazepine-Tegretol", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 100-200 mg dva puta dnevno, uz moguće povećanje do maksimalne doze od 1,200 mg/dan, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule47"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.DETE)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Valproic acid-Depakote", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 7-12 mg/kg/dan, uz moguće povećanje do maksimalne doze od 50 mg/kg/dan, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule48"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Valproic acid-Depakote", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 10-15 mg/kg/dan, uz moguće povećanje do maksimalne doze od 55 mg/kg/dan, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule49"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Valproic acid-Depakote", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 10-18 mg/kg/dan, uz moguće povećanje do maksimalne doze od 60 mg/kg/dan, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule50"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.DETE)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Topiramate-Topamax", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 20-45 mg jednom dnevno, uz moguće povećanje do maksimalne doze od 350 mg/dan, na osnovu odgovora i podnošljivosti.")
    }
end

rule "opis_doze_rule51"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ADOLESCENT)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Topiramate-Topamax", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 25-50 mg jednom dnevno, uz moguće povećanje do maksimalne doze od 400 mg/dan, na osnovu odgovora i podnošljivosti")
    }
end

rule "opis_doze_rule52"
no-loop
when
    $pregled: Pregled()
    $pacijent: Pacijent(this == $pregled.getPacijent(), uzrast == Uzrast.ODRASTAO)
    $filtriranLek: FiltriranLek(pregled == $pregled)
    $lek: Lek(this == $filtriranLek.getLek(), naziv == "Topiramate-Topamax", opisDoze == null)
then
    modify($lek){
        setOpisDoze("Početna doza je 25-50 mg jednom dnevno, uz moguće povećanje do maksimalne doze od 400 mg/dan, na osnovu odgovora i podnošljivosti.")
    }
end


