version: "3"

services:
  #
  # Used for validating mail is sent as expected
  # Host -> smtp
  # Port -> 1025
  #
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"