package signaliStavka;
import com.ftn.sbnz2023tim3.model.modeli.dto.Signal;
import com.ftn.sbnz2023tim3.model.modeli.enumeracije.TipSignala;
import com.ftn.sbnz2023tim3.model.modeli.enumeracije.VisinaSignala;
import com.ftn.sbnz2023tim3.model.modeli.dto.StavkaRezultataSignala;
import com.ftn.sbnz2023tim3.model.modeli.tabele.Pregled;
import com.ftn.sbnz2023tim3.model.modeli.enumeracije.StanjeEEGPregleda;
import com.ftn.sbnz2023tim3.model.modeli.dto.RezultatSignala;
import com.ftn.sbnz2023tim3.model.modeli.dto.RezultatPregleda;
import java.util.Date;
import java.util.Collection;
import java.util.Collections;
import java.util.Arrays;

rule "sumiranje rezultata EEG pregleda"
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.ZAVRSEN)

    $rezultatAlfa: RezultatSignala(pregledId == $pregled.id, tip == TipSignala.ALFA, ukupanBroj != -1, brojNormalnih != -1, brojPovisenih != -1, brojSmanjenih != -1)
    $rezultatBeta: RezultatSignala(pregledId == $pregled.id, tip == TipSignala.BETA, ukupanBroj != -1, brojNormalnih != -1, brojPovisenih != -1, brojSmanjenih != -1)
    $rezultatGama: RezultatSignala(pregledId == $pregled.id, tip == TipSignala.GAMA, ukupanBroj != -1, brojNormalnih != -1, brojPovisenih != -1, brojSmanjenih != -1)
    $rezultatDelta: RezultatSignala(pregledId == $pregled.id, tip == TipSignala.DELTA, ukupanBroj != -1, brojNormalnih != -1, brojPovisenih != -1, brojSmanjenih != -1)
    $rezultatTeta: RezultatSignala(pregledId == $pregled.id, tip == TipSignala.TETA, ukupanBroj != -1, brojNormalnih != -1, brojPovisenih != -1, brojSmanjenih != -1)
then
    double ukupanBrojSignala = Collections.max(Arrays.asList(
                                $rezultatAlfa.getUkupanBroj(),
                                $rezultatBeta.getUkupanBroj(),
                                $rezultatGama.getUkupanBroj(),
                                $rezultatDelta.getUkupanBroj(),
                                $rezultatTeta.getUkupanBroj()
                            ));
    double ukupanProcenatAlfa =  $rezultatAlfa.getUkupanBroj() / ukupanBrojSignala;
    double ukupanProcenatBeta = $rezultatBeta.getUkupanBroj() / ukupanBrojSignala;
    double ukupanProcenatGama = $rezultatGama.getUkupanBroj() / ukupanBrojSignala;
    double ukupanProcenatDelta = $rezultatDelta.getUkupanBroj() / ukupanBrojSignala;
    double ukupanProcenatTeta = $rezultatTeta.getUkupanBroj() / ukupanBrojSignala;

    double procenatEpilepsije = ($rezultatBeta.getBrojPovisenih()/$rezultatBeta.getUkupanBroj() + $rezultatGama.getBrojPovisenih()/$rezultatGama.getUkupanBroj())/2;
    double procenatNesanice = Collections.max(Arrays.asList(
            ($rezultatTeta.getBrojSmanjenih()/$rezultatTeta.getUkupanBroj() + $rezultatDelta.getBrojSmanjenih()/$rezultatDelta.getUkupanBroj())/2,
            ($rezultatTeta.getBrojSmanjenih()/$rezultatTeta.getUkupanBroj() + (1 - ukupanProcenatDelta))/2,
            ($rezultatDelta.getBrojSmanjenih()/$rezultatDelta.getUkupanBroj() + (1 - ukupanProcenatTeta))/2,
            ((1 - ukupanProcenatDelta) + (1 - ukupanProcenatTeta))/2
    ));
    double procenatAlchajmera = Collections.max(Arrays.asList(
            ($rezultatTeta.getBrojPovisenih()/$rezultatTeta.getUkupanBroj() + $rezultatDelta.getBrojPovisenih()/$rezultatDelta.getUkupanBroj() + $rezultatAlfa.getBrojSmanjenih()/$rezultatAlfa.getUkupanBroj())/3,
            ($rezultatTeta.getBrojPovisenih()/$rezultatTeta.getUkupanBroj() + $rezultatDelta.getBrojPovisenih()/$rezultatDelta.getUkupanBroj() + (1 - ukupanProcenatAlfa))/3
    ));
    double procenatADHD = ($rezultatBeta.getBrojPovisenih()/$rezultatBeta.getUkupanBroj() + $rezultatAlfa.getBrojSmanjenih()/$rezultatAlfa.getUkupanBroj())/2;
    System.out.println("procenti, ep: " + procenatEpilepsije + " nesanica: "+ procenatNesanice + " alchajmer: " + procenatAlchajmera + " adhd: " + procenatADHD);
    insert(new RezultatPregleda(procenatEpilepsije, procenatNesanice, procenatAlchajmera, procenatADHD, $pregled));
end


rule "Postavi konacne procente pregleda"
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.ZAVRSEN)
    $rezultat: RezultatPregleda(pregled.id == $pregled.id)
then
    double noviAdhdProcenat = ($pregled.getAdhdProcenat() + $rezultat.getProcenatADHD()) / 2;
    double noviAlchajmerProcenat = ($pregled.getAlchajmerProcenat() + $rezultat.getProcenatAlchajmera()) / 2;
    double noviEpilepsijaProcenat = ($pregled.getEpilepsijaProcenat() + $rezultat.getProcenatEpilepsije()) / 2;
    double noviNesanicaProcenat = ($pregled.getNesanicaProcenat() + $rezultat.getProcenatNesanice()) / 2;

    modify($pregled){
        setAdhdProcenat(noviAdhdProcenat),
        setNesanicaProcenat(noviNesanicaProcenat),
        setEpilepsijaProcenat(noviEpilepsijaProcenat),
        setAlchajmerProcenat(noviAlchajmerProcenat)
    }
end