package signaliStavka;
import com.ftn.sbnz2023tim3.model.modeli.dto.Signal;
import com.ftn.sbnz2023tim3.model.modeli.enumeracije.TipSignala;
import com.ftn.sbnz2023tim3.model.modeli.enumeracije.VisinaSignala;
import com.ftn.sbnz2023tim3.model.modeli.dto.StavkaRezultataSignala;
import com.ftn.sbnz2023tim3.model.modeli.tabele.Pregled;
import com.ftn.sbnz2023tim3.model.modeli.enumeracije.StanjeEEGPregleda;
import com.ftn.sbnz2023tim3.model.modeli.dto.RezultatSignala;
import java.util.Date;
import java.util.Collection;
import java.util.Collections;
import java.util.Arrays;

rule "alfa povisena vrednost"
lock-on-active true
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.U_TOKU)
    $s: Signal(pregled == $pregled.id, frekvencija > 12, amplituda > 55, tip == TipSignala.ALFA)
then
    insert(new StavkaRezultataSignala(new Date(), VisinaSignala.VISOKA, TipSignala.ALFA, $pregled));
end

rule "alfa smanjena vrednost"
lock-on-active true
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.U_TOKU)
    $s: Signal(pregled == $pregled.id, frekvencija < 8, amplituda < 45, tip == TipSignala.ALFA)
then
    insert(new StavkaRezultataSignala(new Date(), VisinaSignala.NISKA, TipSignala.ALFA, $pregled));
end

rule "alfa normalna vrednost"
lock-on-active true
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.U_TOKU)
    $s: Signal(pregled == $pregled.id, frekvencija >= 8 && frekvencija <= 12, amplituda >= 45 && amplituda <= 55, tip == TipSignala.ALFA)
then
    insert(new StavkaRezultataSignala(new Date(), VisinaSignala.NORMALNA, TipSignala.ALFA, $pregled));
end


rule "beta povisena vrednost"
lock-on-active true
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.U_TOKU)
    $s: Signal(pregled == $pregled.id, frekvencija > 30, amplituda > 25, tip == TipSignala.BETA)
then
    insert(new StavkaRezultataSignala(new Date(), VisinaSignala.VISOKA, TipSignala.BETA, $pregled));
end

rule "beta smanjena vrednost"
lock-on-active true
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.U_TOKU)
    $s: Signal(pregled == $pregled.id, frekvencija < 12, amplituda < 15, tip == TipSignala.BETA)
then
    insert(new StavkaRezultataSignala(new Date(), VisinaSignala.NISKA, TipSignala.BETA, $pregled));
end

rule "beta normalna vrednost"
lock-on-active true
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.U_TOKU)
    $s: Signal(pregled == $pregled.id, frekvencija >= 12 && frekvencija <= 30, amplituda >= 15 && amplituda <= 25, tip == TipSignala.BETA)
then
    insert(new StavkaRezultataSignala(new Date(), VisinaSignala.NORMALNA, TipSignala.BETA, $pregled));
end


rule "gama povisena vrednost"
lock-on-active true
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.U_TOKU)
    $s: Signal(pregled == $pregled.id, frekvencija > 100, amplituda > 50, tip == TipSignala.GAMA)
then
    insert(new StavkaRezultataSignala(new Date(), VisinaSignala.VISOKA, TipSignala.GAMA, $pregled));
end

rule "gama smanjena vrednost"
lock-on-active true
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.U_TOKU)
    $s: Signal(pregled == $pregled.id, frekvencija < 30, amplituda < 10, tip == TipSignala.GAMA)
then
    insert(new StavkaRezultataSignala(new Date(), VisinaSignala.NISKA, TipSignala.GAMA, $pregled));
end

rule "gama normalna vrednost"
lock-on-active true
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.U_TOKU)
    $s: Signal(pregled == $pregled.id, frekvencija >= 30 && frekvencija <= 100, amplituda >= 10 && amplituda <= 50, tip == TipSignala.GAMA)
then
    insert(new StavkaRezultataSignala(new Date(), VisinaSignala.NORMALNA, TipSignala.GAMA, $pregled));
end


rule "delta povisena vrednost"
lock-on-active true
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.U_TOKU)
    $s: Signal(pregled == $pregled.id, frekvencija > 4, amplituda > 100, tip == TipSignala.DELTA)
then
    insert(new StavkaRezultataSignala(new Date(), VisinaSignala.VISOKA, TipSignala.DELTA, $pregled));
end

rule "delta smanjena vrednost"
lock-on-active true
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.U_TOKU)
    $s: Signal(pregled == $pregled.id, amplituda < 60, tip == TipSignala.DELTA)
then
    insert(new StavkaRezultataSignala(new Date(), VisinaSignala.NISKA, TipSignala.DELTA, $pregled));
end

rule "delta normalna vrednost"
lock-on-active true
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.U_TOKU)
    $s: Signal(pregled == $pregled.id, frekvencija >= 0 && frekvencija <= 4, amplituda >= 60 && amplituda <= 100, tip == TipSignala.DELTA)
then
    insert(new StavkaRezultataSignala(new Date(), VisinaSignala.NORMALNA, TipSignala.DELTA, $pregled));
end


rule "teta povisena vrednost"
lock-on-active true
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.U_TOKU)
    $s: Signal(pregled == $pregled.id, frekvencija > 8, amplituda > 75, tip == TipSignala.TETA)
then
    insert(new StavkaRezultataSignala(new Date(), VisinaSignala.VISOKA, TipSignala.TETA, $pregled));
end

rule "teta smanjena vrednost"
lock-on-active true
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.U_TOKU)
    $s: Signal(pregled == $pregled.id, frekvencija < 4, amplituda < 65, tip == TipSignala.TETA)
then
    insert(new StavkaRezultataSignala(new Date(), VisinaSignala.NISKA, TipSignala.TETA, $pregled));
end

rule "teta normalna vrednost"
lock-on-active true
when
    $pregled: Pregled(stanjeEEGPregleda == StanjeEEGPregleda.U_TOKU)
    $s: Signal(pregled == $pregled.id, frekvencija >= 4 && frekvencija <= 8, amplituda >= 65 && amplituda <= 75, tip == TipSignala.TETA)
then
    insert(new StavkaRezultataSignala(new Date(), VisinaSignala.NORMALNA, TipSignala.TETA, $pregled));
end
